---
- name: Docker installation
  hosts: servers
  gather_facts: no
  become: yes
  roles:
    - docker

- name: Nginx installation
  hosts: servers
  become: true
  gather_facts: no
  roles:
    - nginx
  tags:
    - nginxinstall

- name: Database installation
  hosts: servers
  become: true
  gather_facts: no
  roles:
    - database
  tags:
    - postgresinstall